### DISCUSSION TITLE
Support semantic OpenAPI expressions for targets

### DISCUSSION THREAD

**Discussion by lornajane** [OAI/Overlay-Specification#128] [Ideas]
For example, how to target all parameters with a name matching a pattern. Or all Array schemas. Rather than needing some JSONPath expression that checks in all the places that these items can go in an OpenAPI file, consider the OpenAPI file as a data structure and access everything more semantically rather than syntactically.

You probably already have linting rules that do some of this stuff, feel free to add them as example here.

**Comment by lornajane** [comment]
Syntax example could be something like these (and if you comment on this, I'll assume you think the overall idea is excellent):

```
target:
  item: operation
  tag: x-special-operation
  method: POST
  
```

We also talked about:

```
target:
  item: schema
  criteria:
    pattern: '*_date'
```
