### DISCUSSION TITLE
Conditional updates

### DISCUSSION THREAD

**Discussion by lornajane** [OAI/Overlay-Specification#132] [Ideas]
How about allowing conditional updates. The use cases I'm thinking of:
 - if target exists (or doesn't)
 - if target is empty (or isn't)

This would let us do things like add missing error responses, but not overwrite any that are already defined.

**Comment by handrews** [comment]
@lornajane an `add` operator that only takes effect if nothing is present at the target would allow implementing document-wide default values, which is something we have been asked about repeatedly.

Current Overlays are great for unconditional globals or merging in fields, but defaults are a bit different.

**Reply by lornajane** [reply]
Yes, agree, we need some sort of weak add or fallback option.

**Comment by hkosova** [comment]
Conditional updates are already possible to an extent by using JSONPath [filter selectors](https://www.rfc-editor.org/rfc/rfc9535.html#section-2.3.5.1).

Example (tested using the Bump.sh CLI):

```yaml
overlay: 1.0.0
info:
  title: Conditional updates
  version: 1.0.0

actions:
  # Add the 401 response to all operations that do NOT already have it
  - target: $.paths..responses[?( !(@['401']) )]
    update:
      '401':
        description: The `Authorization` header is missing or contains an invalid API key.

  # Add description to "MySchema" if it does NOT already have a description
  - target: $.components.schemas.MySchema[?( !(@.description) )]
    update:
      description: Lorem ipsum


  # Add 'x-title: true' to all schemas that have a title
  - target: $.components.schemas.*[?( @.title )]
    update:
      x-title: true
```

<details>
  <summary>Initial OpenAPI document</summary>

```yaml
openapi: 3.1.0
info:
  title: overlay test
  version: 1.0.0

paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
        # Overlay will add the 401 response here, but not under POST that already has 401

    post:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

components:
  schemas:

    # Overlay will add "description: Lorem ipsum" and "x-title: true" to this schema
    MySchema:
      title: Foo
      type: object

    AnotherSchema:
      type: string
      description: This is a string.
```
</details>

<br/>

But I agree that a separate "test if exists / does not exist" operator could make things easier. 

One reason to have a separate "(not) exists" check is that some overlay tools support a strict mode where `target` expressions with no match are flagged as errors/warnings to help catch typos and invalid/outdated JSONPaths. The "(not) exists" operator would help distinguish between invalid JSONPaths and valid checks for missing nodes.
