### ISSUE TITLE
Environment Variables in definition

### ISSUE THREAD

**Issue by Download** [OAI/Overlay-Specification#33]
Sorry if this came up before, I searched but could not find anything.

Environment variables have become something of the de facto mechanism to set server-specific values, then access them from software. The hosting providers I have worked with (AWS, Heroku, OpenShift) all offer features to easily set/import/export them and most software I've seen meant to run on these systems uses it for things like environment specific URLs, secrets etc.

But afaik there is no way to reference environment variables in an OpenAPI definition. 

Would this be a feature to support? I imagine the definition having a section (probably at the top level) that specified a set of environment variables expected to be set, and possibly the default values to use when they are not set. Those variables could then be used in other parts of the definition.

My practical use cases comes from needing to set different authorization urls for different environments. Currently I am rendering swagger.json from JSP to implement this myself, but it seems to me this is a very generic use case that many people will face.

See also e.g.
https://github.com/OAI/OpenAPI-Specification/issues/169
https://github.com/OAI/OpenAPI-Specification/issues/779
https://github.com/swagger-api/swagger-ui/pull/3410

**Comment by lornajane** [comment]
Being able to use an environment variable as a value to use in an update would cover quite a few of these use cases. How about using a `$something` [syntax like Arazzo](https://spec.openapis.org/arazzo/v1.0.1.html#examples) does for `$inputs` and `$response` and things? So we would end up with something like:

```
overlay: 2.0.0
info:
  title: Use Env Vars to add some extra data
  version: 1.0.0
actions:
  - target: $.paths.*.get
    update:
      x-extra: $env.EXTRA_FIELD_VALUE
```

There might be other sources of replacement values so using `$env` makes it clear where this value comes from, and leaves room for more options (like `$target` or `$doc` or .... some other things I haven't thought of it yet).

**Comment by ralfhandl** [comment]
I like the idea, and I am a bit surprised by the matrix feature:
- Which use cases do you have for it? In the example the last update wins and the matrix has no effect. 
- Will it also work with environment variables if I `export foo=("one" "two")` before applying the overlay?

**Comment by baywet** [comment]
I think it could also work with environment variables if we defined a syntax for "arrays" essentially.

The main use case we have for it is that we have a bunch of component schemas we want side cars for.
Right now, our overlay that I can't share publicly, has 40+ actions just for those side car definitions. With a clever JSONPath definition and this matrix ability, we could get it down to 1, making the maintenance significantly easier.

**Comment by baywet** [comment]
Ah... I see, what I forgot in my example for the matrix is that the parameter would ALSO be used in the Target 

So essentially,

```yaml
overlay: 1.2.0
actions:
  - description: makes a matrix projection
    target: '$.components.schemas["${foo}${bar}"]'
    parameters:
      - name: foo
        value_source: inline
        value:
          - one
          - two
      - name: bar
        value_source: inline
        values:
          - A
          - B
    update:
      someProperty: "Fizz ${foo}${bar} buzz"
```

```yaml
overlay: 1.2.0
actions:
  - description: makes a matrix projection
    target: '$.components.schemas["oneA"]'
    update:
      someProperty: "Fizz oneA buzz"
  - description: makes a matrix projection
    target: '$.components.schemas["oneB"]'
    update:
      someProperty: "Fizz oneB buzz"
  - description: makes a matrix projection
    target: '$.components.schemas["twoA"]'
    update:
      someProperty: "Fizz twoA buzz"
  - description: makes a matrix projection
    target: '$.components.schemas["twoB"]'
    update:
      someProperty: "Fizz twoB buzz"
```
