### ISSUE TITLE
Group multiple parameter definitions for better maintainability

### ISSUE THREAD

**Issue by cansik** [OAI/Overlay-Specification#34]
#### Idea

Sometimes you have some parameters you want to provide on every path. At the moment it is possible to reference them with the `$ref` tag. This works great if you have a lot of different parameter combination for each route.

But we now have a complex api with a lot of _optional_ get parameters for every path. Now the problem we encounter is, that if we have to add new parameters to this _get_ parameters, it is very cumbersome and inconvenient to set the reference to them on each path. Often it happens that you forget one.

It would be great if we could group parameter definitions for a better **maintainability** and **usability**.
#### Example

As already presented on [stackoverflow](http://stackoverflow.com/questions/32091430/how-to-group-multiple-parameters-in-swagger-2-0) here an example of the definition (how it could look like):

``` yaml
parameters:
  MetaDataParameters:
    # Meta Data Properties
    - name: id
      in: query
      description: Entry identification number
      required: false
      type: integer

    - name: time_start
      in: query
      description: Start time of flare
      required: false
      type: string

    - name: nar
      in: query
      description: Active region number
      required: false
      type: string
```

And here is how I would like to reference it:

``` yaml
/test/:
  get:
    tags:
      - TEST
    operationId: routes.test
    parameters:
      - $ref: "#/parameters/MetaDataParameters"
    responses:
        200:
          description: OK
```

To get more on the user experience, this definition is much more readable than 20 parameters for each route.
#### Other Ideas?

Have you already thought about something like this or do you want us swagger users to go another way to deal with this problem?

Regards
Florian

**Comment by lornajane** [comment]
There's a valid example further up the thread, and here's my working example in YAML that adds the parameters to all get requests:

```yaml
overlay: 1.0.0
info:
  title: Add parameters to every endpoint
  version: 0.1.0
extends: file:///home/lorna/demo/overlays-traits-example/museum.yaml
actions:
  - target: $.paths.*.get
    update:
      parameters:
        - name: id
          in: query
          description: Entry identification number
          required: false
          type: integer

        - name: time_start
          in: query
          description: Start time of flare
          required: false
          type: string

        - name: nar
          in: query
          description: Active region number
          required: false
          type: string

```

You can do this today using any of the published overlay tools such as the CLIs from Speakeasy and Bump.sh.

I'm going to close this issue since I do feel that the question is answered, but do follow up with new issues or discussions around this feature or similar use cases - we're happy to hear feedback at this early stage.
