### ISSUE TITLE
Allow updating and removing primitive values

### ISSUE THREAD

**Issue by ralfhandl** [OAI/Overlay-Specification#57]
The current text does not allow directly targeting a primitive value, for example a certain string in the `tags` array of an Operation Object, and thus does not allow a convenient/workable way to remove or replace a certain tag name without knowing all other tag names in the `tags` field.

### Proposal

Allow `target` JSON Path expressions to select nodes of all JSON types.

For example allow

```yaml
overlay: 1.0.0
info:
  title: Remove a string from the tags array of all operations
  version: 1.0.0
actions:
  - target: $.paths.*.*.tags[?@ == 'dummy']
    remove: true
```

and

```yaml
overlay: 1.0.0
info:
  title: Replace a string in the tags array of all operations
  version: 1.0.0
actions:
  - target: $.paths.*.*.tags[?@ == 'Foo']
    update: Bar
```
